--- #YAML:1.0
name:                DateTime-Event-Cron-Quartz
version:             0.01
abstract:            OpensSymphony Quartz cron expression processor
license:             ~
author:              
    - Vadim Loginov  <vadim.loginov@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               0.33
    DateTime:                      0.50
    ReadOnly:                      1.03
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
